### ISSUE TITLE
Using on Linux

### ISSUE THREAD

**Issue by kasperkopf** [mashaal/destroyer#8]
hey,
I try to use the player on my linux computer, but it fails. So I used [this instruction](https://github.com/mashaal/destroyer/blob/913ba104a21b5a49c78a4b62f3a8101e81071cce/README.md#semi-working-build-instruction-for-ubuntu), but its incomplete and I tried to rebuild the app. After reinstalling some dependencies i run this app and it works better than previously.

When I play a track (by clicking on a track name or the play-icon), I get this error from JavaScript:
```
Uncaught Exception:
Error: spawn /home/kasperkopf/.config/Electron/ffmpeg/ffplay ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I think there is an issue with the ffmpeg path, because I have a system installation of ffmpeg (should find in my $PATH). I tried to read the code of this app to find this path, but i cant find the line where ffmpeg will be used for playing, except `metadata/editor.js`.

Can someone help me or try to fix this issue?

**Comment by mashaal** [comment]
Hey Kasperkopf, I recently switched from Aurora.js to FFPLAY to handle the playback of files (much better performance) - but it requires downloading the ffmpeg binaries. The error you are receiving is because it cannot find the `ffplay` binary.

I created a script `ffbinaries.js` which you can run to automatically download the correct binaries for your OS - I can verify that it is working on MacOSX.

You can try running it at `npm run ffmpeg`. It can take a couple mins on first run.

Thanks for logging this -- I did heaps of work on the player over the new year, but haven't documented everything yet! 😔

**Comment by kasperkopf** [comment]
Hey thanx for your fast reply!

I didn't know that the script `ffbinaries.js` works for any OS. I run the script, but i get a new error:
```
ffmpeg complete
fs.js:997
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: EISDIR: illegal operation on a directory, unlink './ffmpeg'
    at Object.fs.unlinkSync (fs.js:997:18)
    at WriteStream.<anonymous> (/home/kasperkopf/destroyer/ffbinaries.js:12:8)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:186:7)
    at fs.js:1872:14
    at /home/kasperkopf/destroyer/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:112:15)
``` 

Don't know whats happend with unlink, but the directory exist now. I will keep on this!

**Comment by kasperkopf** [comment]
So finaly it works!

If I use your `ffbinaries.js` its only downloading `ffprobe` and `ffmpeg` because there is no `ffplay` for Linux. See the github page of [ffbinaries-node](https://github.com/vot/ffbinaries-node#included-components).
My solution is to link my system binary of `ffplay` to the created directory by `ffbinaries.js` with 
`ln -s /usr/bin/ffplay ~/destroyer/ffmpeg/`
then change this both lines of `index.js`
```javascript
  player = spawn(`./ffmpeg/ffplay`, [file.path, '-nodisp', '-autoexit'], {stdio: 'ignore'})
  ffmpeg.setFfprobePath(`./ffmpeg/ffprobe`)
```
Now it works on Linux. Maybe I can use [ffplay-static](https://www.npmjs.com/package/ffplay-static) instead of linking the binary.

And can you explain what you want to do with `fs.unlinkSync('./ffmpeg')` ? I uncommented this line.

**Comment by mashaal** [comment]
ahh, i wasn't aware ffplay wasn't available on linux -- or of ffplay-static. I was actually in the process of rewriting the logic behind getting all of these binaries -- not ready to commit yet. I know it's a bit of a mess -- If you have a better solution for grabbing these binaries, please pull request!

Also, you you get a stable build for linux, please pass it on and I can add it to the releases page -- I have gotten a few requests for linux support, and unfortunately I cannot find the time at the moment.

🏇

**Comment by kasperkopf** [comment]
Okay let me find some time at the weekend and I will find a better solution. Its strange that there is no Linux support for `ffplay`. Maybe I find a solution to link the binaries, if there already installed, or I will ask out the guys of `ffbinaries` and `ffplay-static` to add Linux support.

btw I have an autoplay/next play issue. will keep this in mind!

**Comment by mashaal** [comment]
I think there is a bug with autoplay in the last commit i did (not in the released build). I have a commit in progress which will hopefully resolve it (assuming its the same issue)

**Comment by kasperkopf** [comment]
Issue will fixed with #9. Please read my comment why I change some code.  

Can you answer some questions for me?
* Why you use `const userData = app.getPath('userData')` for getting the directory of `ffmpeg`?
* What are you doing in line 114 of `index.js`?

**Comment by mashaal** [comment]
I was having issues getting the ffmpeg path to resolve in production builds (in macOSX), specifically relative paths, UserData gives a absolute path.

Which `index.js`?
